version: "3.9"
name: devops-template

services:
  # Reverse proxy with TLS and auth
  traefik:
    extends:
      file: compose/traefik.yml
      service: traefik
    networks:
      - observability_net

  # Observability core
  clickhouse:
    extends:
      file: compose/observability.yml
      service: clickhouse
  signoz-query-service:
    extends:
      file: compose/observability.yml
      service: signoz-query-service
  signoz-frontend:
    extends:
      file: compose/observability.yml
      service: signoz-frontend
  otel-collector:
    image: signoz/signoz-otel-collector:latest
    depends_on:
      clickhouse:
        condition: service_healthy
        required: true
    environment:
      CLICKHOUSE_ADDRESS: clickhouse:9000
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: "9000"
      CLICKHOUSE_DATABASE: signoz
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: devpass
      CLICKHOUSE_ENDPOINT: tcp://clickhouse:9000
      CLICKHOUSE_DSN: tcp://clickhouse:9000?username=default&password=devpass&database=signoz
      SPAN_STORAGE_TYPE: clickhouse
      LOG_LEVEL: info
    expose:
      - "4318"
    volumes:
      - type: bind
        source: C:/Users/david/devops-template/compose/otel-config/config.yaml
        target: /etc/otel/config.yaml
        read_only: true
    networks:
      - observability_net
    restart: unless-stopped



networks:
  observability_net:
    driver: bridge

volumes:
  clickhouse_data: {}
  signoz_data: {}