receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  clickhousetraces:
    dsn: ${CLICKHOUSE_DSN}
  signozclickhousemetrics:
    dsn: ${CLICKHOUSE_DSN}
  clickhouselogsexporter:
    dsn: ${CLICKHOUSE_DSN}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhousetraces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [signozclickhousemetrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouselogsexporter]
