# compose/observability.yml
name: devops-template

networks:
  observability_net:
    driver: bridge

volumes:
  clickhouse_data: {}
  signoz_data: {}

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    restart: unless-stopped
    networks: [observability_net]
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=devpass
      - CLICKHOUSE_DB=signoz
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./config/clickhouse/config.d/macros.xml:/etc/clickhouse-server/config.d/macros.xml:ro
    healthcheck:
      test: ["CMD-SHELL", "bash -lc '</dev/tcp/127.0.0.1/9000'"]
      interval: 10s
      timeout: 3s
      retries: 10

  signoz-query-service:
    image: signoz/query-service:latest
    restart: unless-stopped
    networks: [observability_net]
    depends_on:
      clickhouse:
        condition: service_healthy
    expose:
      - "8080"
    environment:
      - CLICKHOUSE_ADDRESS=clickhouse:9000
      - CLICKHOUSE_DATABASE=signoz
      - CLICKHOUSE_USERNAME=default
      - CLICKHOUSE_PASSWORD=devpass
    volumes:
      - signoz_data:/var/lib/signoz

  signoz-frontend:
    image: signoz/frontend:latest
    restart: unless-stopped
    networks: [observability_net]
    depends_on:
      - signoz-query-service
    expose:
      - "3301"
    environment:
      - QUERY_SERVICE=http://signoz-query-service:8080

  otel-collector:
    image: signoz/signoz-otel-collector:latest
    command:
      - --config=/etc/otel/config.yaml
    depends_on:
      clickhouse:
        condition: service_healthy
        required: true
    restart: unless-stopped
    networks:
      - observability_net
    expose:
      - "4318"
    environment:
      LOG_LEVEL: "info"
      SPAN_STORAGE_TYPE: "clickhouse"
      CLICKHOUSE_DSN: "tcp://clickhouse:9000?username=default&password=devpass&database=signoz"
      CLICKHOUSE_ENDPOINT: "tcp://clickhouse:9000"
      CLICKHOUSE_ADDRESS: "clickhouse:9000"
      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_PORT: "9000"
      CLICKHOUSE_DATABASE: "signoz"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: "devpass"
    volumes:
      - ./compose/otel-config/config.yaml:/etc/otel/config.yaml:ro
