version: "3.9"

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./config/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro"
      - "./config/traefik/acme.json:/letsencrypt/acme.json"
    environment:
      - LE_EMAIL=${LE_EMAIL}
      - TRAEFIK_BASIC_AUTH=${TRAEFIK_BASIC_AUTH}
      - OTLP_ALLOWLIST=${OTLP_ALLOWLIST}
      - OBS_DOMAIN=${OBS_DOMAIN}
      - OTLP_DOMAIN=${OTLP_DOMAIN}
