name: Lint Docs

on:
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/lint-docs.yml"
  workflow_dispatch:

jobs:
  lint-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Markdown links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose './docs/**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate Mermaid diagrams
        run: |
          npm install -g @mermaid-js/mermaid-cli
          for f in docs/diagrams/*.mmd; do
            echo "[lint-docs] Rendering $f..."
            mmdc -i "$f" -o "/tmp/$(basename "$f" .mmd).svg"
          done
